export const type_colors: { [key: string]: string } = {
  normal: 'type-normal',
  fighting: 'type-fighting',
  flying: 'type-flying',
  poison: 'type-poison',
  ground: 'type-ground',
  rock: 'type-rock',
  bug: 'type-bug',
  ghost: 'type-ghost',
  steel: 'type-steel',
  fire: 'type-fire',
  water: 'type-water',
  grass: 'type-grass',
  electric: 'type-electric',
  psychic: 'type-psychic',
  ice: 'type-ice',
  dragon: 'type-dragon',
  dark: 'type-dark',
  fairy: 'type-fairy',
};
